export const TypeScreens = {
  Planification: 'Planification',
  Magasin: 'Magasin',
  CoupeReception: 'CoupeReception',
  IN_coupe: 'IN_coupe',
  Out_coupe: 'Out_coupe',
  In_Sertissage: 'In_Sertissage',
  Out_Sertissage: 'Out_Sertissage',
  IN_Magasin_fils: 'IN_Magasin_fils',
  Out_Magasin_fils: 'Out_Magasin_fils',
  IN_Preparation: 'IN_Preparation',
  OUT_Preparation: 'OUT_Preparation',
  IN_UTRA_SON: 'IN_UTRA_SON',
  OUT_ULTRA_SON: 'OUT_ULTRA_SON',
  OUT_ULTRA_SON_Confirmed: 'OUT_ULTRA_SON_Confirmed',
  IN_Assemblage: 'IN_Assemblage',
  Out_Assemblage: 'Out_Assemblage',
  ProduitFini: 'produitFini',
};

export const TitreOfScreens = {
  ScreenMagasin: 'Ofs dans magasin',
  ScreenCoupeReception: 'Ofs En attendant la coupe',
  ScreenIN_coupe: 'Ofs en cours de la coupe',
  ScreenOut_coupe: 'Ofs Sortie de la coupe',
  ScreenIn_Sertissage: 'Ofs en cours de la sertissage',
  ScreenOut_Sertissage: 'Ofs Sortie de la sertissage',
  ScreenIN_Magasin_fils: 'Ofs dans magasin des fil',
  ScreenOut_Magasin_fils: 'Ofs Sortie de la magasin des fil',
  ScreenIN_Preparation: 'Ofs en cours de la preparation',
  ScreenOUT_Preparation: 'Ofs Sortie de la preparation',
  ScreenIN_UTRA_SON: 'Ofs en cours de UTRA-SON',
  ScreenOUT_ULTRA_SON: "Ofs Sortie de l'ULTRA-SON",
  ScreenOUT_ULTRA_SONConfirmed: "Ofs Confirmer la Sortie de l'ULTRA-SON",
  ScreenIN_Assemblage: "Ofs en cours de l'assemblage",
  ScreenOut_Assemblage: "Ofs Sortie de l'assemblage",
  ScreenProduction: 'Les produits fini',
};
